import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { EducationContent } from '@/types';

// Mock education content
const mockEducationContent: EducationContent[] = [
  {
    id: 'edu-1',
    title: 'Introduction to Forex Trading',
    description: 'Learn the basics of forex trading, including key terminology, market structure, and how currency pairs work.',
    content: 'Forex trading, also known as foreign exchange trading or currency trading, is the act of buying and selling currencies on the foreign exchange market. The forex market is the largest and most liquid financial market in the world, with trillions of dollars traded daily.\n\nIn forex trading, currencies are always traded in pairs. For example, EUR/USD represents the value of the Euro against the US Dollar. When you buy EUR/USD, you\'re essentially buying Euros while simultaneously selling US Dollars.\n\nThe forex market operates 24 hours a day, five days a week, allowing traders from around the world to trade during normal business hours, after work, or even in the middle of the night.\n\nUnderstanding currency pairs, pips, lots, leverage, and margin is essential for anyone looking to start trading forex. A pip is the smallest price movement in a currency pair, and it\'s used to calculate profits and losses. Lots refer to the size of your trade, with standard, mini, and micro lots representing different amounts of currency units.\n\nLeverage allows traders to control larger positions with a relatively small amount of capital, but it also increases risk. Margin is the amount of money required to open and maintain a leveraged position.\n\nBefore diving into forex trading, it\'s important to develop a solid understanding of technical and fundamental analysis, risk management, and trading psychology. These elements, combined with practice and experience, form the foundation of successful forex trading.',
    category: 'BASICS',
    level: 'BEGINNER',
    duration: 15,
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    readingTimeMinutes: 15,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-01-15'),
    tags: ['Forex', 'Basics', 'Currency Pairs', 'Market Structure']
  },
  {
    id: 'edu-2',
    title: 'Understanding Technical Analysis',
    description: 'Explore the fundamentals of technical analysis, including chart patterns, indicators, and how to apply them in your trading.',
    content: 'Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity, such as past prices and volume. Technical analysts do not attempt to measure a security\'s intrinsic value, but instead use charts and other tools to identify patterns that can suggest future activity.\n\nThe foundation of technical analysis is based on three assumptions: 1) The market discounts everything, 2) Price moves in trends, and 3) History tends to repeat itself.\n\nChart patterns are a key component of technical analysis. Common patterns include head and shoulders, double tops and bottoms, triangles, flags, and pennants. These patterns can signal potential trend reversals or continuations.\n\nTechnical indicators are mathematical calculations based on price, volume, or open interest of a security or contract. They are used to forecast price direction. Indicators can be categorized as trend-following (lagging) indicators or oscillators (leading indicators).\n\nTrend-following indicators include moving averages, MACD, and the Parabolic SAR. These indicators work best in trending markets but may give false signals during sideways or ranging markets.\n\nOscillators, such as RSI, Stochastic, and CCI, are designed to identify overbought or oversold conditions and potential reversals. They work best in ranging markets but may give premature signals during strong trends.\n\nSupport and resistance levels are price points where a currency pair has historically had difficulty moving above (resistance) or below (support). These levels can be identified using horizontal lines, trendlines, Fibonacci retracements, or pivot points.\n\nEffective technical analysis often involves using multiple timeframes and combining different types of indicators to confirm signals. It\'s also important to consider the overall market context and not rely solely on technical indicators for trading decisions.',
    category: 'TECHNICAL',
    level: 'INTERMEDIATE',
    duration: 25,
    imageUrl: 'https://images.unsplash.com/photo-1535320903710-d993d3d77d29?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    readingTimeMinutes: 25,
    createdAt: new Date('2023-02-10'),
    updatedAt: new Date('2023-02-10'),
    tags: ['Technical Analysis', 'Chart Patterns', 'Indicators', 'Trading Strategy']
  },
  {
    id: 'edu-3',
    title: 'Fundamental Analysis in Forex',
    description: 'Learn how economic indicators, central bank policies, and global events impact currency values and trading decisions.',
    content: 'Fundamental analysis in forex trading involves evaluating a currency\'s value based on economic, financial, and geopolitical factors that influence supply and demand. Unlike technical analysis, which focuses on price charts and patterns, fundamental analysis looks at the underlying forces driving currency movements.\n\nEconomic indicators are statistical data points that provide insights into a country\'s economic performance. Key indicators include GDP growth, employment figures, inflation rates, retail sales, and manufacturing indices. These indicators can signal the strength or weakness of an economy, which in turn affects its currency value.\n\nCentral bank policies, particularly interest rate decisions, have a significant impact on currency values. Higher interest rates typically attract foreign investment, increasing demand for the country\'s currency. Central bank statements and forward guidance can also move markets as traders anticipate future policy changes.\n\nGeopolitical events, such as elections, trade disputes, and international conflicts, can create uncertainty and volatility in currency markets. These events can lead to risk-on or risk-off sentiment, affecting the relative value of currencies.\n\nTrading the news is a common fundamental analysis strategy. This involves taking positions based on how actual economic data compares to market expectations. Significant deviations from expectations can lead to sharp currency movements.\n\nThe carry trade is another fundamental strategy that involves borrowing in a low-interest-rate currency and investing in a high-interest-rate currency, profiting from the interest rate differential.\n\nEffective fundamental analysis requires staying informed about global economic developments, understanding how different factors interact, and recognizing which events are most likely to impact specific currency pairs. Many traders combine fundamental analysis with technical analysis to identify high-probability trading opportunities.',
    category: 'FUNDAMENTAL',
    level: 'INTERMEDIATE',
    duration: 20,
    imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    readingTimeMinutes: 20,
    createdAt: new Date('2023-03-05'),
    updatedAt: new Date('2023-03-05'),
    tags: ['Fundamental Analysis', 'Economic Indicators', 'Central Banks', 'Global Events']
  },
  {
    id: 'edu-4',
    title: 'Risk Management Strategies',
    description: 'Discover essential risk management techniques to protect your capital and ensure long-term trading success.',
    content: 'Risk management is arguably the most important aspect of successful trading. Even the best trading strategy will fail without proper risk management. The primary goal of risk management is to preserve capital, which is essential for long-term survival and success in the markets.\n\nPosition sizing is a fundamental risk management technique that determines how much of your capital to risk on each trade. A common rule is to risk no more than 1-2% of your trading capital on any single trade. This approach ensures that a series of losing trades won\'t significantly deplete your account.\n\nStop-loss orders are essential risk management tools that automatically close a position when the price reaches a predetermined level. They help limit potential losses and remove emotional decision-making during adverse market movements. Stop-losses can be set based on technical levels, a fixed percentage, or a specific dollar amount.\n\nTake-profit orders define your exit strategy for profitable trades. Setting realistic profit targets based on support/resistance levels, risk-reward ratios, or other technical factors helps lock in gains and prevents winning trades from turning into losers.\n\nThe risk-reward ratio compares the potential loss of a trade (risk) to its potential gain (reward). A general guideline is to aim for a minimum risk-reward ratio of 1:2, meaning the potential profit is at least twice the potential loss.\n\nDiversification involves spreading risk across different currency pairs or markets. Correlations between pairs should be considered to avoid overexposure to similar market movements.\n\nRisk management also includes psychological aspects, such as maintaining discipline, following your trading plan, and avoiding emotional trading decisions. Keeping a trading journal to track and analyze your trades can help identify patterns and improve risk management over time.\n\nRemember that protecting your capital during drawdowns is crucial. It\'s much easier to recover from a 10% loss than a 50% loss, which would require a 100% gain just to break even.',
    category: 'RISK_MANAGEMENT',
    level: 'BEGINNER',
    duration: 18,
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1415&q=80',
    readingTimeMinutes: 18,
    createdAt: new Date('2023-04-20'),
    updatedAt: new Date('2023-04-20'),
    tags: ['Risk Management', 'Position Sizing', 'Stop Loss', 'Risk-Reward Ratio']
  },
  {
    id: 'edu-5',
    title: 'Trading Psychology: Mastering Your Emotions',
    description: 'Learn how psychological factors influence trading decisions and develop mental strategies for trading success.',
    content: 'Trading psychology refers to the emotional and mental state of a trader that influences their trading decisions. Many traders find that managing emotions is more challenging than analyzing markets or developing strategies.\n\nFear and greed are two primary emotions that can derail trading performance. Fear can cause traders to exit profitable positions too early, hesitate to enter trades, or fail to cut losses. Greed can lead to overtrading, excessive risk-taking, or holding losing positions too long in hopes of a reversal.\n\nCognitive biases also affect trading decisions. Confirmation bias leads traders to seek information that supports their existing views while ignoring contradictory evidence. Recency bias causes overemphasis on recent events when making predictions. Loss aversion makes traders more sensitive to losses than equivalent gains, potentially leading to poor risk management.\n\nDeveloping a trading mindset involves several key principles:\n\n1. Discipline: Following your trading plan and rules consistently, even when emotions suggest otherwise.\n\n2. Patience: Waiting for high-probability setups rather than forcing trades out of boredom or FOMO (fear of missing out).\n\n3. Objectivity: Analyzing markets based on evidence rather than hopes or fears.\n\n4. Resilience: Bouncing back from losses and learning from mistakes without becoming discouraged.\n\n5. Detachment: Separating your self-worth from your trading results and treating trading as a probability game.\n\nPractical techniques for improving trading psychology include:\n\n- Maintaining a trading journal to identify emotional patterns\n- Implementing a structured trading plan with clear rules\n- Using visualization and mindfulness techniques\n- Taking breaks after significant wins or losses\n- Setting realistic expectations and focusing on process over outcomes\n\nRemember that developing strong trading psychology is a continuous process that requires self-awareness and practice. Even experienced traders must constantly monitor and manage their psychological state to maintain peak performance.',
    category: 'PSYCHOLOGY',
    level: 'INTERMEDIATE',
    duration: 22,
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    readingTimeMinutes: 22,
    createdAt: new Date('2023-05-15'),
    updatedAt: new Date('2023-05-15'),
    tags: ['Trading Psychology', 'Emotions', 'Discipline', 'Mindset']
  },
  {
    id: 'edu-6',
    title: 'Advanced Chart Patterns',
    description: 'Master complex chart patterns like harmonic patterns, Elliott Wave theory, and advanced candlestick formations.',
    content: 'Advanced chart patterns go beyond basic formations and offer sophisticated ways to analyze price action. These patterns often require more experience to identify correctly but can provide valuable insights for trading decisions.\n\nHarmonic patterns are precise geometric price formations that use Fibonacci ratios to identify potential reversal points. Common harmonic patterns include the Gartley, Butterfly, Bat, and Crab patterns. Each pattern has specific Fibonacci measurements between its points (labeled X, A, B, C, D) that must be met for valid identification. When properly formed, these patterns can provide high-probability trading opportunities with clearly defined risk levels.\n\nElliott Wave Theory, developed by Ralph Nelson Elliott, suggests that markets move in repetitive cycles of five impulsive waves and three corrective waves. The theory incorporates fractal geometry, meaning these wave patterns exist across all timeframes. Mastering Elliott Wave analysis requires understanding wave characteristics, Fibonacci relationships between waves, and various rules and guidelines that govern wave formation. While complex, Elliott Wave can provide insights into both trend direction and potential reversal points.\n\nAdvanced candlestick patterns include complex formations like Three Buddha, Gimmee Bar, Tweezer Tops/Bottoms, and Three-Line Strike. These patterns often combine multiple candlesticks and consider the surrounding market context. Proper interpretation requires understanding not just the pattern itself but also its location within the broader trend, volume confirmation, and other supporting factors.\n\nPrice action analysis at key market levels can reveal advanced patterns like the Spring and Upthrust (from Wyckoff methodology), which show institutional manipulation at support and resistance levels. Order flow analysis, which examines the interaction between buying and selling pressure, can complement these patterns.\n\nWhen trading advanced patterns, it\'s essential to use multiple timeframe analysis, confirm signals with other technical tools, and always implement proper risk management. These patterns should be viewed as probability-based setups rather than guaranteed outcomes.',
    category: 'TECHNICAL',
    level: 'ADVANCED',
    duration: 30,
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    readingTimeMinutes: 30,
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2023-06-10'),
    tags: ['Advanced Patterns', 'Harmonic Patterns', 'Elliott Wave', 'Price Action']
  },
  {
    id: 'edu-7',
    title: 'Developing a Trading Plan',
    description: 'Learn how to create a comprehensive trading plan that defines your strategy, risk management, and trading goals.',
    content: 'A trading plan is a comprehensive document that outlines your approach to trading, including your strategy, risk management rules, and goals. It serves as a roadmap for your trading activities and helps maintain consistency and discipline.\n\nThe first step in developing a trading plan is defining your trading goals. These should be specific, measurable, achievable, relevant, and time-bound (SMART). Examples include "Achieve a 20% annual return" or "Generate $500 monthly income from trading." Your goals should align with your financial situation, time commitment, and risk tolerance.\n\nYour trading strategy is the core of your plan. It should clearly define:\n\n1. Markets and instruments you\'ll trade (specific currency pairs, etc.)\n2. Timeframes you\'ll focus on (daily, 4-hour, 1-hour charts, etc.)\n3. Entry criteria (specific setups, indicators, or patterns that trigger trades)\n4. Exit criteria (take-profit levels, trailing stops, time-based exits)\n5. Position sizing and risk parameters\n\nRisk management rules are critical for long-term success. Your plan should specify:\n\n- Maximum risk per trade (typically 1-2% of account)\n- Maximum open risk at any time (e.g., no more than 5% of account)\n- Drawdown thresholds that trigger a trading pause or review\n- Correlation considerations to avoid overexposure\n\nYour trading schedule should account for your lifestyle and the markets you trade. Define when you\'ll analyze markets, place trades, and review performance. Consider market hours, economic releases, and your personal obligations.\n\nA record-keeping system is essential for tracking performance and improving over time. Your plan should include how you\'ll log trades, what metrics you\'ll track, and how often you\'ll review your results.\n\nFinally, include a process for regularly reviewing and updating your trading plan. Markets evolve, and your approach should adapt accordingly. Set specific intervals (monthly, quarterly) to assess your plan\'s effectiveness and make necessary adjustments.\n\nRemember that a trading plan is personal and should reflect your individual circumstances, goals, and trading style. The most effective plan is one that you can consistently follow.',
    category: 'BASICS',
    level: 'BEGINNER',
    duration: 20,
    imageUrl: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    readingTimeMinutes: 20,
    createdAt: new Date('2023-07-05'),
    updatedAt: new Date('2023-07-05'),
    tags: ['Trading Plan', 'Strategy', 'Goals', 'Risk Management']
  },
  {
    id: 'edu-8',
    title: 'Understanding Market Correlations',
    description: 'Explore how different currency pairs and markets correlate and how to use this knowledge in your trading strategy.',
    content: 'Market correlation refers to the statistical relationship between two financial instruments. In forex trading, understanding correlations between currency pairs can help diversify risk, identify trading opportunities, and avoid overexposure to similar market movements.\n\nCorrelations are measured on a scale from -1 to +1. A correlation of +1 indicates perfect positive correlation, meaning the pairs move in the same direction. A correlation of -1 indicates perfect negative correlation, meaning the pairs move in opposite directions. A correlation near zero suggests no significant relationship between the pairs.\n\nMajor correlation relationships in forex include:\n\n1. Currency pairs with the same base currency often show positive correlation. For example, EUR/USD and EUR/JPY tend to move in the same direction because they both rise when the Euro strengthens.\n\n2. Currency pairs with opposite structures often show negative correlation. For example, EUR/USD and USD/CHF typically move in opposite directions because USD is the base currency in one pair and the quote currency in the other.\n\n3. Commodity currencies (AUD, CAD, NZD) often correlate with their respective commodity prices. AUD correlates with gold and iron ore prices, CAD with oil prices, and NZD with agricultural commodity prices.\n\n4. Safe-haven currencies like JPY, CHF, and USD often move inversely to risk sentiment in global markets. During market uncertainty, these currencies typically strengthen as investors seek safety.\n\nCorrelations are not static and can change over time due to shifting economic conditions, central bank policies, or geopolitical factors. It\'s important to regularly update your correlation analysis.\n\nTraders can use correlation in several ways:\n\n- Diversification: Avoid taking multiple positions in highly correlated pairs, as this effectively increases your risk exposure.\n\n- Confirmation: Use correlated pairs to confirm signals. If EUR/USD shows a bullish signal, check if GBP/USD shows similar behavior.\n\n- Hedging: Take positions in negatively correlated pairs to reduce overall portfolio risk.\n\n- Arbitrage: Identify temporary divergences in typically correlated pairs for potential mean-reversion trades.\n\nCorrelation analysis can be performed using correlation coefficients, correlation matrices, or visual chart comparison. Many trading platforms and websites offer correlation tools to simplify this analysis.',
    category: 'FUNDAMENTAL',
    level: 'INTERMEDIATE',
    duration: 25,
    imageUrl: 'https://images.unsplash.com/photo-1559526324-593bc073d938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    readingTimeMinutes: 25,
    createdAt: new Date('2023-08-12'),
    updatedAt: new Date('2023-08-12'),
    tags: ['Correlations', 'Risk Management', 'Market Analysis', 'Diversification']
  },
  {
    id: 'edu-9',
    title: 'Mastering Fibonacci Retracements',
    description: 'Learn how to effectively use Fibonacci retracements and extensions to identify potential support, resistance, and price targets.',
    content: 'Fibonacci retracements are a popular technical analysis tool based on the Fibonacci sequence and the golden ratio. Traders use Fibonacci levels to identify potential support and resistance areas, retracement levels, and price targets.\n\nThe Fibonacci sequence (0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...) has a unique property: after the first few numbers, the ratio of any number to the next number approaches 0.618 (the golden ratio), and the ratio of any number to the number two positions ahead approaches 0.382.\n\nIn trading, the key Fibonacci retracement levels are 23.6%, 38.2%, 50% (not actually a Fibonacci ratio but commonly used), 61.8%, and 78.6%. These percentages represent potential retracement levels when a market pulls back after a significant move.\n\nTo apply Fibonacci retracements:\n\n1. Identify a clear trend or significant price move (the swing low to swing high in an uptrend, or swing high to swing low in a downtrend).\n\n2. Draw the Fibonacci retracement tool from the start to the end of this move. The tool will automatically calculate and display the retracement levels.\n\n3. Watch for price reactions at these levels. They often act as support in uptrends or resistance in downtrends.\n\nFibonacci extensions (100%, 161.8%, 261.8%, 423.6%) are used to project potential price targets beyond the original move. They\'re particularly useful for setting profit targets in trending markets.\n\nFibonacci expansion levels are similar to extensions but use three points (the initial move and the first retracement) to project future price movements.\n\nAdvanced Fibonacci applications include:\n\n- Fibonacci time zones for timing potential market turns\n- Fibonacci fans and arcs for identifying support/resistance areas\n- Fibonacci clusters, where multiple Fibonacci levels from different swings converge, creating stronger support/resistance zones\n\nFor best results, use Fibonacci tools in conjunction with other technical analysis methods like trend lines, chart patterns, or indicators. The most reliable Fibonacci levels are those that align with other significant technical levels or previous price reactions.\n\nRemember that Fibonacci levels are not magical or guaranteed to work. They represent areas where many traders may be placing orders, creating a self-fulfilling tendency for prices to react at these levels.',
    category: 'TECHNICAL',
    level: 'INTERMEDIATE',
    duration: 22,
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    readingTimeMinutes: 22,
    createdAt: new Date('2023-09-08'),
    updatedAt: new Date('2023-09-08'),
    tags: ['Fibonacci', 'Technical Analysis', 'Support and Resistance', 'Price Targets']
  },
  {
    id: 'edu-10',
    title: 'Central Banks and Monetary Policy',
    description: 'Understand how central bank decisions impact currency markets and how to trade around monetary policy announcements.',
    content: 'Central banks play a crucial role in forex markets as they control monetary policy, which directly affects currency values. Understanding how central banks operate and how to interpret their actions is essential for fundamental forex analysis.\n\nThe primary central banks that influence forex markets include the Federal Reserve (Fed), European Central Bank (ECB), Bank of Japan (BOJ), Bank of England (BOE), Swiss National Bank (SNB), Bank of Canada (BOC), Reserve Bank of Australia (RBA), and Reserve Bank of New Zealand (RBNZ).\n\nCentral banks have various monetary policy tools:\n\n1. Interest rates: The primary tool for most central banks. Higher rates typically strengthen a currency by attracting foreign capital seeking better returns. Lower rates often weaken a currency.\n\n2. Quantitative easing (QE): The purchase of government bonds or other securities to increase money supply and stimulate the economy. QE typically weakens a currency.\n\n3. Quantitative tightening (QT): The reduction of the central bank\'s balance sheet by selling securities or allowing them to mature without replacement. QT typically strengthens a currency.\n\n4. Forward guidance: Communication about future policy intentions. Clear hawkish guidance (suggesting tighter policy) typically strengthens a currency, while dovish guidance (suggesting looser policy) typically weakens it.\n\n5. Direct intervention: Buying or selling currencies in the forex market to influence exchange rates. This is less common among major central banks but can cause significant market movements when it occurs.\n\nTrading around central bank announcements requires preparation and risk management:\n\n1. Know the schedule: Central banks publish their meeting calendars in advance. Mark these dates on your trading calendar.\n\n2. Understand market expectations: Research what policy changes analysts expect. Markets react to the difference between actual announcements and expectations.\n\n3. Watch for forward guidance: Often, the statement accompanying the decision or the press conference afterward contains valuable information about future policy direction.\n\n4. Be aware of increased volatility: Markets can move rapidly and unpredictably during and after central bank announcements. Consider reducing position sizes or staying out of the market entirely if you\'re uncomfortable with this volatility.\n\n5. Look for the second move: The initial market reaction sometimes reverses once traders have fully digested the information. The more sustainable move often comes after this initial volatility.\n\nCentral bank divergence—when central banks move in opposite policy directions—can create strong and sustained forex trends. For example, if the Fed is raising rates while the ECB is cutting rates, this policy divergence would likely create a strong downtrend in EUR/USD.',
    category: 'FUNDAMENTAL',
    level: 'ADVANCED',
    duration: 28,
    imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80',
    readingTimeMinutes: 28,
    createdAt: new Date('2023-10-15'),
    updatedAt: new Date('2023-10-15'),
    tags: ['Central Banks', 'Monetary Policy', 'Interest Rates', 'Economic Events']
  }
];

interface EducationState {
  articles: EducationContent[];
  completedArticles: string[];
  isLoading: boolean;
  error: string | null;
  
  // Actions
  fetchArticles: () => Promise<void>;
  getArticleById: (id: string) => EducationContent | undefined;
  markArticleAsCompleted: (id: string) => void;
  clearCompletedArticles: () => void;
}

export const useEducationStore = create<EducationState>()(
  persist(
    (set, get) => ({
      articles: [],
      completedArticles: [],
      isLoading: false,
      error: null,
      
      fetchArticles: async () => {
        set({ isLoading: true, error: null });
        
        try {
          // In a real app, we would fetch articles from an API
          // For now, we'll use mock data
          await new Promise(resolve => setTimeout(resolve, 1000));
          set({ 
            articles: mockEducationContent,
            isLoading: false 
          });
        } catch (error) {
          set({ 
            error: 'Failed to fetch articles',
            isLoading: false 
          });
        }
      },
      
      getArticleById: (id: string) => {
        return get().articles.find((article) => article.id === id);
      },
      
      markArticleAsCompleted: (id: string) => {
        set((state) => {
          if (state.completedArticles.includes(id)) {
            return state;
          }
          
          return {
            completedArticles: [...state.completedArticles, id]
          };
        });
      },
      
      clearCompletedArticles: () => {
        set({ completedArticles: [] });
      }
    }),
    {
      name: 'education-storage',
      storage: createJSONStorage(() => AsyncStorage),
      partialize: (state) => ({
        completedArticles: state.completedArticles
      })
    }
  )
);